{
 "title": "SSL/TLS Exporter",
 "description": "Shows certificate expiration times, as well as failed ssl connects",
 "tags": [
  "ssl",
  "tls"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ssl_probe_success, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Unique Certificates",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(max(ssl_cert_not_after{instance=~\"$instance\",job=~\"$job\"}) by (issuer_cn,serial_no))"
    }
   ]
  },
  {
   "title": "Total Probe Targets",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(max(ssl_cert_not_after{instance=~\"$instance\",job=~\"$job\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Failed SSL Connects History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(up{job=~\"$job\", instance=~\"$instance\"} == 0 or ssl_probe_success{job=~\"$job\", instance=~\"$instance\"} == 0)^0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed SSL Connects - $job",
   "type": "table",
   "description": "Possible reasons:\n- site is down\n- server is down\n- certificate has expired\n- certificate's CA is not trusted by the exporter\n- other connection errors\n- other certificate errors",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "repeat": "job",
   "targets": [
    {
     "expr": "ssl_probe_success{instance=~\"$instance\",job=~\"$job\"} == 0"
    }
   ]
  },
  {
   "title": "SSL Certificates",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "((ssl_cert_not_after{instance=~\"$instance\",job=~\"$job\"} - time())/24/60/60)"
    }
   ]
  }
 ]
}