apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace | quote }}
  name: {{ include "releasename" $ | quote }}
  labels: {{- include "labels" $ | nindent 4 }}
  annotations: {{- toYaml $.Values.service.annotations | nindent 4 }}
spec:
  ports:
    - name: exporter
      port: {{ $.Values.service.port }}
      protocol: TCP
      targetPort: exporter
  selector: {{- include "matchLabels" $ | nindent 4 }}
  sessionAffinity: {{ $.Values.service.sessionAffinity | quote }}
  type: {{ $.Values.service.type | quote }}
