global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'ssl'
    metrics_path: /probe
    static_configs:
      - targets:
        - 'google.co.uk:443'
        - 'prometheus.io:443'
        - 'example.com:443'
        - 'helloworld.letsencrypt.org:443'
        - 'expired.badssl.com:443'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9219  # SSL exporter.
  - job_name: 'ssl-files'
    metrics_path: /probe
    params:
      module: ["file"]
      target: ["/etc/ssl/**/*.pem"]
    static_configs:
      - targets:
          - 127.0.0.1:9219
  - job_name: 'jks-files'
    metrics_path: /probe
    params:
      module: ["jks"]
      target: ["/usr/java/jdk1.8.0_74/jre/lib/security/cacerts"]
    static_configs:
      - targets:
          - 127.0.0.1:9219
  - job_name: 'ssl-kubernetes-secrets'
    metrics_path: /probe
    params:
      module: ["kubernetes"]
      target: ["kube-system/*"]
    static_configs:
      - targets:
          - 127.0.0.1:9219
